// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: meta/cluster.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                                 // identify a storage node
	Ip                string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`                                                                  // ip of the storage node
	Port              uint64   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                                             // port of the storage node
	CreatedAt         uint64   `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                  // created time of the storage node
	UpdatedAt         uint64   `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                  // updated time of the storage node
	Peers             []uint64 `protobuf:"varint,6,rep,packed,name=peers,proto3" json:"peers,omitempty"`                                                    // peers of the storage node
	Cap               uint64   `protobuf:"varint,7,opt,name=cap,proto3" json:"cap,omitempty"`                                                               // capacity of the storage node
	Usage             uint64   `protobuf:"varint,8,opt,name=usage,proto3" json:"usage,omitempty"`                                                           // usage of the storage node
	PhysicalVolumeIds []uint64 `protobuf:"varint,9,rep,packed,name=physical_volume_ids,json=physicalVolumeIds,proto3" json:"physical_volume_ids,omitempty"` // physical volumes in the storage node
	TcpPort           uint64   `protobuf:"varint,10,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
}

func (x *StorageNode) Reset() {
	*x = StorageNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageNode) ProtoMessage() {}

func (x *StorageNode) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageNode.ProtoReflect.Descriptor instead.
func (*StorageNode) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *StorageNode) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StorageNode) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *StorageNode) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StorageNode) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StorageNode) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *StorageNode) GetPeers() []uint64 {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *StorageNode) GetCap() uint64 {
	if x != nil {
		return x.Cap
	}
	return 0
}

func (x *StorageNode) GetUsage() uint64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *StorageNode) GetPhysicalVolumeIds() []uint64 {
	if x != nil {
		return x.PhysicalVolumeIds
	}
	return nil
}

func (x *StorageNode) GetTcpPort() uint64 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

type GetStorageNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStorageNode) Reset() {
	*x = GetStorageNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStorageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageNode) ProtoMessage() {}

func (x *GetStorageNode) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageNode.ProtoReflect.Descriptor instead.
func (*GetStorageNode) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{1}
}

type ListStorageNodes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListStorageNodes) Reset() {
	*x = ListStorageNodes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStorageNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageNodes) ProtoMessage() {}

func (x *ListStorageNodes) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageNodes.ProtoReflect.Descriptor instead.
func (*ListStorageNodes) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{2}
}

type AddStorageNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddStorageNode) Reset() {
	*x = AddStorageNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStorageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStorageNode) ProtoMessage() {}

func (x *AddStorageNode) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStorageNode.ProtoReflect.Descriptor instead.
func (*AddStorageNode) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{3}
}

type GetCandidateStorage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCandidateStorage) Reset() {
	*x = GetCandidateStorage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandidateStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateStorage) ProtoMessage() {}

func (x *GetCandidateStorage) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateStorage.ProtoReflect.Descriptor instead.
func (*GetCandidateStorage) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{4}
}

type PatchStorageNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PatchStorageNode) Reset() {
	*x = PatchStorageNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchStorageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchStorageNode) ProtoMessage() {}

func (x *PatchStorageNode) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchStorageNode.ProtoReflect.Descriptor instead.
func (*PatchStorageNode) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{5}
}

type GetStorageNode_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Arg:
	//
	//	*GetStorageNode_Request_Id
	//	*GetStorageNode_Request_Address
	Arg isGetStorageNode_Request_Arg `protobuf_oneof:"Arg"`
}

func (x *GetStorageNode_Request) Reset() {
	*x = GetStorageNode_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStorageNode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageNode_Request) ProtoMessage() {}

func (x *GetStorageNode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageNode_Request.ProtoReflect.Descriptor instead.
func (*GetStorageNode_Request) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{1, 0}
}

func (m *GetStorageNode_Request) GetArg() isGetStorageNode_Request_Arg {
	if m != nil {
		return m.Arg
	}
	return nil
}

func (x *GetStorageNode_Request) GetId() uint64 {
	if x, ok := x.GetArg().(*GetStorageNode_Request_Id); ok {
		return x.Id
	}
	return 0
}

func (x *GetStorageNode_Request) GetAddress() string {
	if x, ok := x.GetArg().(*GetStorageNode_Request_Address); ok {
		return x.Address
	}
	return ""
}

type isGetStorageNode_Request_Arg interface {
	isGetStorageNode_Request_Arg()
}

type GetStorageNode_Request_Id struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetStorageNode_Request_Address struct {
	Address string `protobuf:"bytes,2,opt,name=address,proto3,oneof"`
}

func (*GetStorageNode_Request_Id) isGetStorageNode_Request_Arg() {}

func (*GetStorageNode_Request_Address) isGetStorageNode_Request_Arg() {}

type GetStorageNode_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageNode *StorageNode `protobuf:"bytes,1,opt,name=storage_node,json=storageNode,proto3" json:"storage_node,omitempty"`
}

func (x *GetStorageNode_Response) Reset() {
	*x = GetStorageNode_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStorageNode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageNode_Response) ProtoMessage() {}

func (x *GetStorageNode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageNode_Response.ProtoReflect.Descriptor instead.
func (*GetStorageNode_Response) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetStorageNode_Response) GetStorageNode() *StorageNode {
	if x != nil {
		return x.StorageNode
	}
	return nil
}

type ListStorageNodes_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListStorageNodes_Request) Reset() {
	*x = ListStorageNodes_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStorageNodes_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageNodes_Request) ProtoMessage() {}

func (x *ListStorageNodes_Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageNodes_Request.ProtoReflect.Descriptor instead.
func (*ListStorageNodes_Request) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{2, 0}
}

type ListStorageNodes_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageNodes []*StorageNode `protobuf:"bytes,1,rep,name=storage_nodes,json=storageNodes,proto3" json:"storage_nodes,omitempty"`
}

func (x *ListStorageNodes_Response) Reset() {
	*x = ListStorageNodes_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListStorageNodes_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageNodes_Response) ProtoMessage() {}

func (x *ListStorageNodes_Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageNodes_Response.ProtoReflect.Descriptor instead.
func (*ListStorageNodes_Response) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ListStorageNodes_Response) GetStorageNodes() []*StorageNode {
	if x != nil {
		return x.StorageNodes
	}
	return nil
}

type AddStorageNode_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip      string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // ip of the storage node
	Port    uint64 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // port of the storage node
	Cap     uint64 `protobuf:"varint,3,opt,name=cap,proto3" json:"cap,omitempty"`   // capacity of the storage node
	TcpPort uint64 `protobuf:"varint,4,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
}

func (x *AddStorageNode_Request) Reset() {
	*x = AddStorageNode_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStorageNode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStorageNode_Request) ProtoMessage() {}

func (x *AddStorageNode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStorageNode_Request.ProtoReflect.Descriptor instead.
func (*AddStorageNode_Request) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AddStorageNode_Request) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddStorageNode_Request) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AddStorageNode_Request) GetCap() uint64 {
	if x != nil {
		return x.Cap
	}
	return 0
}

func (x *AddStorageNode_Request) GetTcpPort() uint64 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

type AddStorageNode_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageNode *StorageNode `protobuf:"bytes,1,opt,name=storage_node,json=storageNode,proto3" json:"storage_node,omitempty"`
}

func (x *AddStorageNode_Response) Reset() {
	*x = AddStorageNode_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddStorageNode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStorageNode_Response) ProtoMessage() {}

func (x *AddStorageNode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStorageNode_Response.ProtoReflect.Descriptor instead.
func (*AddStorageNode_Response) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{3, 1}
}

func (x *AddStorageNode_Response) GetStorageNode() *StorageNode {
	if x != nil {
		return x.StorageNode
	}
	return nil
}

type GetCandidateStorage_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCandidateStorage_Request) Reset() {
	*x = GetCandidateStorage_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandidateStorage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateStorage_Request) ProtoMessage() {}

func (x *GetCandidateStorage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateStorage_Request.ProtoReflect.Descriptor instead.
func (*GetCandidateStorage_Request) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{4, 0}
}

type GetCandidateStorage_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primary   *StorageNode `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary *StorageNode `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
}

func (x *GetCandidateStorage_Response) Reset() {
	*x = GetCandidateStorage_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandidateStorage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateStorage_Response) ProtoMessage() {}

func (x *GetCandidateStorage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateStorage_Response.ProtoReflect.Descriptor instead.
func (*GetCandidateStorage_Response) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetCandidateStorage_Response) GetPrimary() *StorageNode {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *GetCandidateStorage_Response) GetSecondary() *StorageNode {
	if x != nil {
		return x.Secondary
	}
	return nil
}

type PatchStorageNode_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PhysicalVolumeUsage map[uint64]uint64 `protobuf:"bytes,2,rep,name=physical_volume_usage,json=physicalVolumeUsage,proto3" json:"physical_volume_usage,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *PatchStorageNode_Request) Reset() {
	*x = PatchStorageNode_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchStorageNode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchStorageNode_Request) ProtoMessage() {}

func (x *PatchStorageNode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchStorageNode_Request.ProtoReflect.Descriptor instead.
func (*PatchStorageNode_Request) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{5, 0}
}

func (x *PatchStorageNode_Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchStorageNode_Request) GetPhysicalVolumeUsage() map[uint64]uint64 {
	if x != nil {
		return x.PhysicalVolumeUsage
	}
	return nil
}

type PatchStorageNode_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StorageNode *StorageNode `protobuf:"bytes,1,opt,name=storage_node,json=storageNode,proto3" json:"storage_node,omitempty"`
}

func (x *PatchStorageNode_Response) Reset() {
	*x = PatchStorageNode_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_cluster_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchStorageNode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchStorageNode_Response) ProtoMessage() {}

func (x *PatchStorageNode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_cluster_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchStorageNode_Response.ProtoReflect.Descriptor instead.
func (*PatchStorageNode_Response) Descriptor() ([]byte, []int) {
	return file_meta_cluster_proto_rawDescGZIP(), []int{5, 1}
}

func (x *PatchStorageNode_Response) GetStorageNode() *StorageNode {
	if x != nil {
		return x.StorageNode
	}
	return nil
}

var File_meta_cluster_proto protoreflect.FileDescriptor

var file_meta_cluster_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x22, 0x88, 0x02, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x61,
	0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x63, 0x61, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x75, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x11, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x49,
	0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x63, 0x70, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x63, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x9a, 0x01,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x1a, 0x3e, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x41, 0x72, 0x67,
	0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0c,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x69, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0x09,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x4a, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0xb6, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x1a, 0x5a, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x61, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x63, 0x61, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x63, 0x70,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x63, 0x70,
	0x50, 0x6f, 0x72, 0x74, 0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3c, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x9a,
	0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x78, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a,
	0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x37, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x22, 0xb5, 0x02, 0x0a, 0x10,
	0x50, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x1a, 0xd6, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x73, 0x0a, 0x15,
	0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x67, 0x61,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x13, 0x70, 0x68,
	0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x46, 0x0a, 0x18, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x48, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x32, 0x86, 0x04, 0x0a, 0x0e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x41, 0x64,
	0x64, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x24, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x26, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6c, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x29, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x67, 0x61,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x10, 0x50, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x2e, 0x67, 0x61,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x2e, 0x66, 0x61, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x74, 0x65, 0x63, 0x68, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2f, 0x67, 0x61, 0x69, 0x61,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_cluster_proto_rawDescOnce sync.Once
	file_meta_cluster_proto_rawDescData = file_meta_cluster_proto_rawDesc
)

func file_meta_cluster_proto_rawDescGZIP() []byte {
	file_meta_cluster_proto_rawDescOnce.Do(func() {
		file_meta_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_cluster_proto_rawDescData)
	})
	return file_meta_cluster_proto_rawDescData
}

var file_meta_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_meta_cluster_proto_goTypes = []interface{}{
	(*StorageNode)(nil),                  // 0: hugo.v1.meta.StorageNode
	(*GetStorageNode)(nil),               // 1: hugo.v1.meta.GetStorageNode
	(*ListStorageNodes)(nil),             // 2: hugo.v1.meta.ListStorageNodes
	(*AddStorageNode)(nil),               // 3: hugo.v1.meta.AddStorageNode
	(*GetCandidateStorage)(nil),          // 4: hugo.v1.meta.GetCandidateStorage
	(*PatchStorageNode)(nil),             // 5: hugo.v1.meta.PatchStorageNode
	(*GetStorageNode_Request)(nil),       // 6: hugo.v1.meta.GetStorageNode.Request
	(*GetStorageNode_Response)(nil),      // 7: hugo.v1.meta.GetStorageNode.Response
	(*ListStorageNodes_Request)(nil),     // 8: hugo.v1.meta.ListStorageNodes.Request
	(*ListStorageNodes_Response)(nil),    // 9: hugo.v1.meta.ListStorageNodes.Response
	(*AddStorageNode_Request)(nil),       // 10: hugo.v1.meta.AddStorageNode.Request
	(*AddStorageNode_Response)(nil),      // 11: hugo.v1.meta.AddStorageNode.Response
	(*GetCandidateStorage_Request)(nil),  // 12: hugo.v1.meta.GetCandidateStorage.Request
	(*GetCandidateStorage_Response)(nil), // 13: hugo.v1.meta.GetCandidateStorage.Response
	(*PatchStorageNode_Request)(nil),     // 14: hugo.v1.meta.PatchStorageNode.Request
	(*PatchStorageNode_Response)(nil),    // 15: hugo.v1.meta.PatchStorageNode.Response
	nil,                                  // 16: hugo.v1.meta.PatchStorageNode.Request.PhysicalVolumeUsageEntry
}
var file_meta_cluster_proto_depIdxs = []int32{
	0,  // 0: hugo.v1.meta.GetStorageNode.Response.storage_node:type_name -> hugo.v1.meta.StorageNode
	0,  // 1: hugo.v1.meta.ListStorageNodes.Response.storage_nodes:type_name -> hugo.v1.meta.StorageNode
	0,  // 2: hugo.v1.meta.AddStorageNode.Response.storage_node:type_name -> hugo.v1.meta.StorageNode
	0,  // 3: hugo.v1.meta.GetCandidateStorage.Response.primary:type_name -> hugo.v1.meta.StorageNode
	0,  // 4: hugo.v1.meta.GetCandidateStorage.Response.secondary:type_name -> hugo.v1.meta.StorageNode
	16, // 5: hugo.v1.meta.PatchStorageNode.Request.physical_volume_usage:type_name -> hugo.v1.meta.PatchStorageNode.Request.PhysicalVolumeUsageEntry
	0,  // 6: hugo.v1.meta.PatchStorageNode.Response.storage_node:type_name -> hugo.v1.meta.StorageNode
	10, // 7: hugo.v1.meta.ClusterService.AddStorageNode:input_type -> hugo.v1.meta.AddStorageNode.Request
	6,  // 8: hugo.v1.meta.ClusterService.GetStorageNode:input_type -> hugo.v1.meta.GetStorageNode.Request
	8,  // 9: hugo.v1.meta.ClusterService.ListStorageNodes:input_type -> hugo.v1.meta.ListStorageNodes.Request
	12, // 10: hugo.v1.meta.ClusterService.GetCandidateStorage:input_type -> hugo.v1.meta.GetCandidateStorage.Request
	14, // 11: hugo.v1.meta.ClusterService.PatchStorageNode:input_type -> hugo.v1.meta.PatchStorageNode.Request
	11, // 12: hugo.v1.meta.ClusterService.AddStorageNode:output_type -> hugo.v1.meta.AddStorageNode.Response
	7,  // 13: hugo.v1.meta.ClusterService.GetStorageNode:output_type -> hugo.v1.meta.GetStorageNode.Response
	9,  // 14: hugo.v1.meta.ClusterService.ListStorageNodes:output_type -> hugo.v1.meta.ListStorageNodes.Response
	13, // 15: hugo.v1.meta.ClusterService.GetCandidateStorage:output_type -> hugo.v1.meta.GetCandidateStorage.Response
	15, // 16: hugo.v1.meta.ClusterService.PatchStorageNode:output_type -> hugo.v1.meta.PatchStorageNode.Response
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_meta_cluster_proto_init() }
func file_meta_cluster_proto_init() {
	if File_meta_cluster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meta_cluster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStorageNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStorageNodes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStorageNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandidateStorage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchStorageNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStorageNode_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStorageNode_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStorageNodes_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListStorageNodes_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStorageNode_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddStorageNode_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandidateStorage_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandidateStorage_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchStorageNode_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_cluster_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchStorageNode_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_meta_cluster_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*GetStorageNode_Request_Id)(nil),
		(*GetStorageNode_Request_Address)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_cluster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meta_cluster_proto_goTypes,
		DependencyIndexes: file_meta_cluster_proto_depIdxs,
		MessageInfos:      file_meta_cluster_proto_msgTypes,
	}.Build()
	File_meta_cluster_proto = out.File
	file_meta_cluster_proto_rawDesc = nil
	file_meta_cluster_proto_goTypes = nil
	file_meta_cluster_proto_depIdxs = nil
}
