// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: meta/snapshot.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// snapshot id
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RootIno       uint64 `protobuf:"varint,2,opt,name=root_ino,json=rootIno,proto3" json:"root_ino,omitempty"`
	TransactionId uint64 `protobuf:"varint,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// key: ino
	// value: BlockMapRef
	InoBlockMaps map[uint64]*BlockMapRef `protobuf:"bytes,4,rep,name=ino_block_maps,json=inoBlockMaps,proto3" json:"ino_block_maps,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Snapshot) GetRootIno() uint64 {
	if x != nil {
		return x.RootIno
	}
	return 0
}

func (x *Snapshot) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *Snapshot) GetInoBlockMaps() map[uint64]*BlockMapRef {
	if x != nil {
		return x.InoBlockMaps
	}
	return nil
}

type BlockMapRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ino uint64 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`
	// key: block index in file
	// value: transaction_id = 3;
	BlockMap map[uint64]uint64 `protobuf:"bytes,3,rep,name=block_map,json=blockMap,proto3" json:"block_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *BlockMapRef) Reset() {
	*x = BlockMapRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockMapRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMapRef) ProtoMessage() {}

func (x *BlockMapRef) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMapRef.ProtoReflect.Descriptor instead.
func (*BlockMapRef) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *BlockMapRef) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *BlockMapRef) GetBlockMap() map[uint64]uint64 {
	if x != nil {
		return x.BlockMap
	}
	return nil
}

type CreateSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSnapshot) Reset() {
	*x = CreateSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshot) ProtoMessage() {}

func (x *CreateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshot.ProtoReflect.Descriptor instead.
func (*CreateSnapshot) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{2}
}

type ListSnapshots struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSnapshots) Reset() {
	*x = ListSnapshots{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSnapshots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshots) ProtoMessage() {}

func (x *ListSnapshots) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshots.ProtoReflect.Descriptor instead.
func (*ListSnapshots) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{3}
}

type DeleteSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSnapshot) Reset() {
	*x = DeleteSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshot) ProtoMessage() {}

func (x *DeleteSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshot.ProtoReflect.Descriptor instead.
func (*DeleteSnapshot) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{4}
}

type CreateSnapshot_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootIno       string `protobuf:"bytes,1,opt,name=root_ino,json=rootIno,proto3" json:"root_ino,omitempty"` // create a snapshot under a root
	TransactionId uint64 `protobuf:"varint,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *CreateSnapshot_Request) Reset() {
	*x = CreateSnapshot_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSnapshot_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshot_Request) ProtoMessage() {}

func (x *CreateSnapshot_Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshot_Request.ProtoReflect.Descriptor instead.
func (*CreateSnapshot_Request) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateSnapshot_Request) GetRootIno() string {
	if x != nil {
		return x.RootIno
	}
	return ""
}

func (x *CreateSnapshot_Request) GetTransactionId() uint64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type CreateSnapshot_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SnapshotId string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"` // in actually, it is a virtualVolumeID
}

func (x *CreateSnapshot_Response) Reset() {
	*x = CreateSnapshot_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSnapshot_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshot_Response) ProtoMessage() {}

func (x *CreateSnapshot_Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshot_Response.ProtoReflect.Descriptor instead.
func (*CreateSnapshot_Response) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CreateSnapshot_Response) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type ListSnapshots_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSnapshots_Request) Reset() {
	*x = ListSnapshots_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSnapshots_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshots_Request) ProtoMessage() {}

func (x *ListSnapshots_Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshots_Request.ProtoReflect.Descriptor instead.
func (*ListSnapshots_Request) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{3, 0}
}

type ListSnapshots_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snapshots []*Snapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
}

func (x *ListSnapshots_Response) Reset() {
	*x = ListSnapshots_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSnapshots_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshots_Response) ProtoMessage() {}

func (x *ListSnapshots_Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshots_Response.ProtoReflect.Descriptor instead.
func (*ListSnapshots_Response) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ListSnapshots_Response) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type DeleteSnapshot_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SnapshotId string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
}

func (x *DeleteSnapshot_Request) Reset() {
	*x = DeleteSnapshot_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSnapshot_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshot_Request) ProtoMessage() {}

func (x *DeleteSnapshot_Request) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshot_Request.ProtoReflect.Descriptor instead.
func (*DeleteSnapshot_Request) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DeleteSnapshot_Request) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type DeleteSnapshot_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSnapshot_Response) Reset() {
	*x = DeleteSnapshot_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_snapshot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSnapshot_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshot_Response) ProtoMessage() {}

func (x *DeleteSnapshot_Response) ProtoReflect() protoreflect.Message {
	mi := &file_meta_snapshot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshot_Response.ProtoReflect.Descriptor instead.
func (*DeleteSnapshot_Response) Descriptor() ([]byte, []int) {
	return file_meta_snapshot_proto_rawDescGZIP(), []int{4, 1}
}

var File_meta_snapshot_proto protoreflect.FileDescriptor

var file_meta_snapshot_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x22, 0x88, 0x02, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x49, 0x6e, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x4e, 0x0a, 0x0e, 0x69, 0x6e, 0x6f, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x6d, 0x61, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x61, 0x69,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x2e, 0x49, 0x6e, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x69, 0x6e, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x61,
	0x70, 0x73, 0x1a, 0x5a, 0x0a, 0x11, 0x49, 0x6e, 0x6f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x61,
	0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x61, 0x70,
	0x52, 0x65, 0x66, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa2,
	0x01, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x66, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x6e, 0x6f,
	0x12, 0x44, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x66, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x4d, 0x61, 0x70, 0x1a, 0x3b, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x1a, 0x4b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x49, 0x6e, 0x6f, 0x12, 0x25, 0x0a, 0x0e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x1a, 0x2b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x64,
	0x22, 0x5c, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x73, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x40, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x52, 0x09, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x22, 0x48,
	0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x1a, 0x2a, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x49, 0x64, 0x1a, 0x0a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xab, 0x02, 0x0a, 0x0f, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x24,
	0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x4c,
	0x69, 0x73, 0x74, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x67,
	0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x24, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x24, 0x2e, 0x67, 0x61, 0x69, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x2e, 0x66, 0x61,
	0x73, 0x74, 0x6f, 0x6e, 0x65, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61,
	0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2f, 0x67, 0x61, 0x69, 0x61, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x62, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_snapshot_proto_rawDescOnce sync.Once
	file_meta_snapshot_proto_rawDescData = file_meta_snapshot_proto_rawDesc
)

func file_meta_snapshot_proto_rawDescGZIP() []byte {
	file_meta_snapshot_proto_rawDescOnce.Do(func() {
		file_meta_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_snapshot_proto_rawDescData)
	})
	return file_meta_snapshot_proto_rawDescData
}

var file_meta_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_meta_snapshot_proto_goTypes = []interface{}{
	(*Snapshot)(nil),                // 0: hugo.v1.meta.Snapshot
	(*BlockMapRef)(nil),             // 1: hugo.v1.meta.BlockMapRef
	(*CreateSnapshot)(nil),          // 2: hugo.v1.meta.CreateSnapshot
	(*ListSnapshots)(nil),           // 3: hugo.v1.meta.ListSnapshots
	(*DeleteSnapshot)(nil),          // 4: hugo.v1.meta.DeleteSnapshot
	nil,                             // 5: hugo.v1.meta.Snapshot.InoBlockMapsEntry
	nil,                             // 6: hugo.v1.meta.BlockMapRef.BlockMapEntry
	(*CreateSnapshot_Request)(nil),  // 7: hugo.v1.meta.CreateSnapshot.Request
	(*CreateSnapshot_Response)(nil), // 8: hugo.v1.meta.CreateSnapshot.Response
	(*ListSnapshots_Request)(nil),   // 9: hugo.v1.meta.ListSnapshots.Request
	(*ListSnapshots_Response)(nil),  // 10: hugo.v1.meta.ListSnapshots.Response
	(*DeleteSnapshot_Request)(nil),  // 11: hugo.v1.meta.DeleteSnapshot.Request
	(*DeleteSnapshot_Response)(nil), // 12: hugo.v1.meta.DeleteSnapshot.Response
}
var file_meta_snapshot_proto_depIdxs = []int32{
	5,  // 0: hugo.v1.meta.Snapshot.ino_block_maps:type_name -> hugo.v1.meta.Snapshot.InoBlockMapsEntry
	6,  // 1: hugo.v1.meta.BlockMapRef.block_map:type_name -> hugo.v1.meta.BlockMapRef.BlockMapEntry
	1,  // 2: hugo.v1.meta.Snapshot.InoBlockMapsEntry.value:type_name -> hugo.v1.meta.BlockMapRef
	0,  // 3: hugo.v1.meta.ListSnapshots.Response.snapshots:type_name -> hugo.v1.meta.Snapshot
	7,  // 4: hugo.v1.meta.SnapshotService.CreateSnapshot:input_type -> hugo.v1.meta.CreateSnapshot.Request
	9,  // 5: hugo.v1.meta.SnapshotService.ListSnapshots:input_type -> hugo.v1.meta.ListSnapshots.Request
	11, // 6: hugo.v1.meta.SnapshotService.DeleteSnapshot:input_type -> hugo.v1.meta.DeleteSnapshot.Request
	8,  // 7: hugo.v1.meta.SnapshotService.CreateSnapshot:output_type -> hugo.v1.meta.CreateSnapshot.Response
	10, // 8: hugo.v1.meta.SnapshotService.ListSnapshots:output_type -> hugo.v1.meta.ListSnapshots.Response
	12, // 9: hugo.v1.meta.SnapshotService.DeleteSnapshot:output_type -> hugo.v1.meta.DeleteSnapshot.Response
	7,  // [7:10] is the sub-list for method output_type
	4,  // [4:7] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_meta_snapshot_proto_init() }
func file_meta_snapshot_proto_init() {
	if File_meta_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meta_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockMapRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSnapshots); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSnapshot_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSnapshot_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSnapshots_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSnapshots_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSnapshot_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_snapshot_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSnapshot_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meta_snapshot_proto_goTypes,
		DependencyIndexes: file_meta_snapshot_proto_depIdxs,
		MessageInfos:      file_meta_snapshot_proto_msgTypes,
	}.Build()
	File_meta_snapshot_proto = out.File
	file_meta_snapshot_proto_rawDesc = nil
	file_meta_snapshot_proto_goTypes = nil
	file_meta_snapshot_proto_depIdxs = nil
}
