// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockState int32

const (
	BlockState_LOCAL    BlockState = 0 // local only
	BlockState_LOCAL_S3 BlockState = 1 // sync on both
	BlockState_S3_ONLY  BlockState = 2 // s3 only
)

// Enum value maps for BlockState.
var (
	BlockState_name = map[int32]string{
		0: "LOCAL",
		1: "LOCAL_S3",
		2: "S3_ONLY",
	}
	BlockState_value = map[string]int32{
		"LOCAL":    0,
		"LOCAL_S3": 1,
		"S3_ONLY":  2,
	}
)

func (x BlockState) Enum() *BlockState {
	p := new(BlockState)
	*p = x
	return p
}

func (x BlockState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockState) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_storage_proto_enumTypes[0].Descriptor()
}

func (BlockState) Type() protoreflect.EnumType {
	return &file_storage_storage_proto_enumTypes[0]
}

func (x BlockState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockState.Descriptor instead.
func (BlockState) EnumDescriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{0}
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`    // block content
	Len   uint32 `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`     // length of block
	Index uint64 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"` // index of current block
	Crc32 uint32 `protobuf:"varint,5,opt,name=crc32,proto3" json:"crc32,omitempty"` // crc32 of block
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetLen() uint32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *Block) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Block) GetCrc32() uint32 {
	if x != nil {
		return x.Crc32
	}
	return 0
}

type Read struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Read) Reset() {
	*x = Read{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{1}
}

type StreamReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *StreamReadResponse) Reset() {
	*x = StreamReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamReadResponse) ProtoMessage() {}

func (x *StreamReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamReadResponse.ProtoReflect.Descriptor instead.
func (*StreamReadResponse) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StreamReadResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// WriteOneBlock just write one block at the given index or append to the tail.
type WriteBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WriteBlock) Reset() {
	*x = WriteBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlock) ProtoMessage() {}

func (x *WriteBlock) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlock.ProtoReflect.Descriptor instead.
func (*WriteBlock) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{3}
}

type StreamWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamWrite) Reset() {
	*x = StreamWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWrite) ProtoMessage() {}

func (x *StreamWrite) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWrite.ProtoReflect.Descriptor instead.
func (*StreamWrite) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{4}
}

type DeleteBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBlock) Reset() {
	*x = DeleteBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlock) ProtoMessage() {}

func (x *DeleteBlock) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlock.ProtoReflect.Descriptor instead.
func (*DeleteBlock) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{5}
}

type ListBlocks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBlocks) Reset() {
	*x = ListBlocks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocks) ProtoMessage() {}

func (x *ListBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocks.ProtoReflect.Descriptor instead.
func (*ListBlocks) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{6}
}

type EvictBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EvictBlock) Reset() {
	*x = EvictBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvictBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictBlock) ProtoMessage() {}

func (x *EvictBlock) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictBlock.ProtoReflect.Descriptor instead.
func (*EvictBlock) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{7}
}

type RecycleSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecycleSpace) Reset() {
	*x = RecycleSpace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleSpace) ProtoMessage() {}

func (x *RecycleSpace) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleSpace.ProtoReflect.Descriptor instead.
func (*RecycleSpace) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{8}
}

type Warmup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Warmup) Reset() {
	*x = Warmup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Warmup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warmup) ProtoMessage() {}

func (x *Warmup) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warmup.ProtoReflect.Descriptor instead.
func (*Warmup) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{9}
}

type Read_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ino      uint64   `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`                          // read from which file?
	BlockIds []string `protobuf:"bytes,4,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"` // the block ids
}

func (x *Read_Request) Reset() {
	*x = Read_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Read_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read_Request) ProtoMessage() {}

func (x *Read_Request) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read_Request.ProtoReflect.Descriptor instead.
func (*Read_Request) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Read_Request) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *Read_Request) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

type Read_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *Read_Response) Reset() {
	*x = Read_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Read_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read_Response) ProtoMessage() {}

func (x *Read_Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read_Response.ProtoReflect.Descriptor instead.
func (*Read_Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Read_Response) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type WriteBlock_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ino       uint64  `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`                                 // write to which file?
	BlockIdx  *uint64 `protobuf:"varint,2,opt,name=block_idx,json=blockIdx,proto3,oneof" json:"block_idx,omitempty"` // write which block? if not given, just append
	BlockData []byte  `protobuf:"bytes,3,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`     // write a block; create if not exist; overwrite if exist;
	Crc32     uint32  `protobuf:"varint,5,opt,name=crc32,proto3" json:"crc32,omitempty"`                             // crc32 of block
}

func (x *WriteBlock_Request) Reset() {
	*x = WriteBlock_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBlock_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlock_Request) ProtoMessage() {}

func (x *WriteBlock_Request) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlock_Request.ProtoReflect.Descriptor instead.
func (*WriteBlock_Request) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{3, 0}
}

func (x *WriteBlock_Request) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *WriteBlock_Request) GetBlockIdx() uint64 {
	if x != nil && x.BlockIdx != nil {
		return *x.BlockIdx
	}
	return 0
}

func (x *WriteBlock_Request) GetBlockData() []byte {
	if x != nil {
		return x.BlockData
	}
	return nil
}

func (x *WriteBlock_Request) GetCrc32() uint32 {
	if x != nil {
		return x.Crc32
	}
	return 0
}

type WriteBlock_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ino      uint64 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`
	BlockIdx uint64 `protobuf:"varint,2,opt,name=block_idx,json=blockIdx,proto3" json:"block_idx,omitempty"` // index of written block
	BlockId  string `protobuf:"bytes,3,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`     // content hash of the block
	VolId    uint64 `protobuf:"varint,4,opt,name=vol_id,json=volId,proto3" json:"vol_id,omitempty"`
	NodeId   uint64 `protobuf:"varint,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Crc32    uint32 `protobuf:"varint,6,opt,name=crc32,proto3" json:"crc32,omitempty"`
	Len      uint64 `protobuf:"varint,7,opt,name=len,proto3" json:"len,omitempty"`
}

func (x *WriteBlock_Response) Reset() {
	*x = WriteBlock_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBlock_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBlock_Response) ProtoMessage() {}

func (x *WriteBlock_Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBlock_Response.ProtoReflect.Descriptor instead.
func (*WriteBlock_Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{3, 1}
}

func (x *WriteBlock_Response) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *WriteBlock_Response) GetBlockIdx() uint64 {
	if x != nil {
		return x.BlockIdx
	}
	return 0
}

func (x *WriteBlock_Response) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *WriteBlock_Response) GetVolId() uint64 {
	if x != nil {
		return x.VolId
	}
	return 0
}

func (x *WriteBlock_Response) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *WriteBlock_Response) GetCrc32() uint32 {
	if x != nil {
		return x.Crc32
	}
	return 0
}

func (x *WriteBlock_Response) GetLen() uint64 {
	if x != nil {
		return x.Len
	}
	return 0
}

type StreamWrite_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ino uint64 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"` // write to which file?
}

func (x *StreamWrite_Header) Reset() {
	*x = StreamWrite_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamWrite_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWrite_Header) ProtoMessage() {}

func (x *StreamWrite_Header) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWrite_Header.ProtoReflect.Descriptor instead.
func (*StreamWrite_Header) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{4, 0}
}

func (x *StreamWrite_Header) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

type StreamWrite_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mode:
	//
	//	*StreamWrite_Request_Header
	//	*StreamWrite_Request_Block
	Mode isStreamWrite_Request_Mode `protobuf_oneof:"mode"`
}

func (x *StreamWrite_Request) Reset() {
	*x = StreamWrite_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamWrite_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWrite_Request) ProtoMessage() {}

func (x *StreamWrite_Request) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWrite_Request.ProtoReflect.Descriptor instead.
func (*StreamWrite_Request) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{4, 1}
}

func (m *StreamWrite_Request) GetMode() isStreamWrite_Request_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (x *StreamWrite_Request) GetHeader() *StreamWrite_Header {
	if x, ok := x.GetMode().(*StreamWrite_Request_Header); ok {
		return x.Header
	}
	return nil
}

func (x *StreamWrite_Request) GetBlock() []byte {
	if x, ok := x.GetMode().(*StreamWrite_Request_Block); ok {
		return x.Block
	}
	return nil
}

type isStreamWrite_Request_Mode interface {
	isStreamWrite_Request_Mode()
}

type StreamWrite_Request_Header struct {
	Header *StreamWrite_Header `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type StreamWrite_Request_Block struct {
	Block []byte `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

func (*StreamWrite_Request_Header) isStreamWrite_Request_Mode() {}

func (*StreamWrite_Request_Block) isStreamWrite_Request_Mode() {}

type StreamWrite_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockIdx []uint64 `protobuf:"varint,2,rep,packed,name=block_idx,json=blockIdx,proto3" json:"block_idx,omitempty"` // index of written block
}

func (x *StreamWrite_Response) Reset() {
	*x = StreamWrite_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamWrite_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWrite_Response) ProtoMessage() {}

func (x *StreamWrite_Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWrite_Response.ProtoReflect.Descriptor instead.
func (*StreamWrite_Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{4, 2}
}

func (x *StreamWrite_Response) GetBlockIdx() []uint64 {
	if x != nil {
		return x.BlockIdx
	}
	return nil
}

type DeleteBlock_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ino      uint64   `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`                          // read from which file?
	BlockIds []string `protobuf:"bytes,4,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"` // the block ids
}

func (x *DeleteBlock_Request) Reset() {
	*x = DeleteBlock_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlock_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlock_Request) ProtoMessage() {}

func (x *DeleteBlock_Request) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlock_Request.ProtoReflect.Descriptor instead.
func (*DeleteBlock_Request) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DeleteBlock_Request) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *DeleteBlock_Request) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

type DeleteBlock_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockIds []string `protobuf:"bytes,4,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"` // the block ids
}

func (x *DeleteBlock_Response) Reset() {
	*x = DeleteBlock_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlock_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlock_Response) ProtoMessage() {}

func (x *DeleteBlock_Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlock_Response.ProtoReflect.Descriptor instead.
func (*DeleteBlock_Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{5, 1}
}

func (x *DeleteBlock_Response) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

type ListBlocks_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBlocks_Request) Reset() {
	*x = ListBlocks_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlocks_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocks_Request) ProtoMessage() {}

func (x *ListBlocks_Request) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocks_Request.ProtoReflect.Descriptor instead.
func (*ListBlocks_Request) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{6, 0}
}

type ListBlocks_BlockMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId string     `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	NodeId  uint64     `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VolId   uint64     `protobuf:"varint,3,opt,name=vol_id,json=volId,proto3" json:"vol_id,omitempty"`
	Size    uint64     `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	State   BlockState `protobuf:"varint,5,opt,name=state,proto3,enum=hugo.v1.storage.BlockState" json:"state,omitempty"`
	Crc     uint32     `protobuf:"varint,6,opt,name=crc,proto3" json:"crc,omitempty"`
}

func (x *ListBlocks_BlockMeta) Reset() {
	*x = ListBlocks_BlockMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlocks_BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocks_BlockMeta) ProtoMessage() {}

func (x *ListBlocks_BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocks_BlockMeta.ProtoReflect.Descriptor instead.
func (*ListBlocks_BlockMeta) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{6, 1}
}

func (x *ListBlocks_BlockMeta) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ListBlocks_BlockMeta) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ListBlocks_BlockMeta) GetVolId() uint64 {
	if x != nil {
		return x.VolId
	}
	return 0
}

func (x *ListBlocks_BlockMeta) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListBlocks_BlockMeta) GetState() BlockState {
	if x != nil {
		return x.State
	}
	return BlockState_LOCAL
}

func (x *ListBlocks_BlockMeta) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

type ListBlocks_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*ListBlocks_BlockMeta `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *ListBlocks_Response) Reset() {
	*x = ListBlocks_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlocks_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocks_Response) ProtoMessage() {}

func (x *ListBlocks_Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocks_Response.ProtoReflect.Descriptor instead.
func (*ListBlocks_Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{6, 2}
}

func (x *ListBlocks_Response) GetBlocks() []*ListBlocks_BlockMeta {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type EvictBlock_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expired uint64 `protobuf:"varint,1,opt,name=expired,proto3" json:"expired,omitempty"`
}

func (x *EvictBlock_Request) Reset() {
	*x = EvictBlock_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvictBlock_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictBlock_Request) ProtoMessage() {}

func (x *EvictBlock_Request) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictBlock_Request.ProtoReflect.Descriptor instead.
func (*EvictBlock_Request) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{7, 0}
}

func (x *EvictBlock_Request) GetExpired() uint64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

type EvictBlock_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockIds []string `protobuf:"bytes,1,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
}

func (x *EvictBlock_Response) Reset() {
	*x = EvictBlock_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvictBlock_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictBlock_Response) ProtoMessage() {}

func (x *EvictBlock_Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictBlock_Response.ProtoReflect.Descriptor instead.
func (*EvictBlock_Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{7, 1}
}

func (x *EvictBlock_Response) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

type RecycleSpace_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecycleSpace_Request) Reset() {
	*x = RecycleSpace_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleSpace_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleSpace_Request) ProtoMessage() {}

func (x *RecycleSpace_Request) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleSpace_Request.ProtoReflect.Descriptor instead.
func (*RecycleSpace_Request) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{8, 0}
}

type RecycleSpace_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockIds []string `protobuf:"bytes,1,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
}

func (x *RecycleSpace_Response) Reset() {
	*x = RecycleSpace_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecycleSpace_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleSpace_Response) ProtoMessage() {}

func (x *RecycleSpace_Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleSpace_Response.ProtoReflect.Descriptor instead.
func (*RecycleSpace_Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{8, 1}
}

func (x *RecycleSpace_Response) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

type Warmup_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Warmup_Request) Reset() {
	*x = Warmup_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Warmup_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warmup_Request) ProtoMessage() {}

func (x *Warmup_Request) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warmup_Request.ProtoReflect.Descriptor instead.
func (*Warmup_Request) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{9, 0}
}

type Warmup_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockIds []string `protobuf:"bytes,1,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
}

func (x *Warmup_Response) Reset() {
	*x = Warmup_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_storage_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Warmup_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warmup_Response) ProtoMessage() {}

func (x *Warmup_Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warmup_Response.ProtoReflect.Descriptor instead.
func (*Warmup_Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{9, 1}
}

func (x *Warmup_Response) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

var File_storage_storage_proto protoreflect.FileDescriptor

var file_storage_storage_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x69, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x72, 0x63, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x72,
	0x63, 0x33, 0x32, 0x22, 0x7c, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x1a, 0x38, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x6e, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x64, 0x73, 0x1a, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x22, 0x42, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0xbe, 0x02, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x80, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69,
	0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64,
	0x78, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x72, 0x63, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x63, 0x72, 0x63, 0x33, 0x32, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x78, 0x1a, 0xac, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x69, 0x6e, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x69, 0x64, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x64, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x76, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x72, 0x63, 0x33, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63,
	0x72, 0x63, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x1a, 0x1a, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69,
	0x6e, 0x6f, 0x1a, 0x68, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x1a, 0x27, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x64, 0x78, 0x22, 0x70, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x38, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x6e,
	0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x1a, 0x27,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x22, 0x94, 0x02, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0xaf, 0x01, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x31,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x63, 0x72, 0x63, 0x1a, 0x49, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22, 0x5a,
	0x0a, 0x0a, 0x45, 0x76, 0x69, 0x63, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x23, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x64, 0x1a, 0x27, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x22, 0x42, 0x0a, 0x0c, 0x52, 0x65,
	0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x22, 0x3c,
	0x0a, 0x06, 0x57, 0x61, 0x72, 0x6d, 0x75, 0x70, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x2a, 0x32, 0x0a, 0x0a,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f,
	0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x5f, 0x53,
	0x33, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x33, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x02,
	0x32, 0x97, 0x06, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x61,
	0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x61, 0x69,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x52,
	0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67,
	0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x12, 0x24, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x12, 0x5a, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x24, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x23, 0x2e, 0x67, 0x61, 0x69,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0a, 0x45, 0x76, 0x69, 0x63, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x23, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x76, 0x69, 0x63, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d,
	0x0a, 0x0c, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x25,
	0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a,
	0x06, 0x57, 0x61, 0x72, 0x6d, 0x75, 0x70, 0x12, 0x1f, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x57, 0x61, 0x72, 0x6d, 0x75, 0x70,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x61, 0x69, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x57, 0x61, 0x72, 0x6d, 0x75,
	0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69,
	0x74, 0x2e, 0x66, 0x61, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x61, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x2f, 0x67, 0x61, 0x69, 0x61, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_storage_proto_rawDescOnce sync.Once
	file_storage_storage_proto_rawDescData = file_storage_storage_proto_rawDesc
)

func file_storage_storage_proto_rawDescGZIP() []byte {
	file_storage_storage_proto_rawDescOnce.Do(func() {
		file_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_storage_proto_rawDescData)
	})
	return file_storage_storage_proto_rawDescData
}

var file_storage_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_storage_storage_proto_goTypes = []interface{}{
	(BlockState)(0),               // 0: hugo.v1.storage.BlockState
	(*Block)(nil),                 // 1: hugo.v1.storage.Block
	(*Read)(nil),                  // 2: hugo.v1.storage.Read
	(*StreamReadResponse)(nil),    // 3: hugo.v1.storage.StreamReadResponse
	(*WriteBlock)(nil),            // 4: hugo.v1.storage.WriteBlock
	(*StreamWrite)(nil),           // 5: hugo.v1.storage.StreamWrite
	(*DeleteBlock)(nil),           // 6: hugo.v1.storage.DeleteBlock
	(*ListBlocks)(nil),            // 7: hugo.v1.storage.ListBlocks
	(*EvictBlock)(nil),            // 8: hugo.v1.storage.EvictBlock
	(*RecycleSpace)(nil),          // 9: hugo.v1.storage.RecycleSpace
	(*Warmup)(nil),                // 10: hugo.v1.storage.Warmup
	(*Read_Request)(nil),          // 11: hugo.v1.storage.Read.Request
	(*Read_Response)(nil),         // 12: hugo.v1.storage.Read.Response
	(*WriteBlock_Request)(nil),    // 13: hugo.v1.storage.WriteBlock.Request
	(*WriteBlock_Response)(nil),   // 14: hugo.v1.storage.WriteBlock.Response
	(*StreamWrite_Header)(nil),    // 15: hugo.v1.storage.StreamWrite.Header
	(*StreamWrite_Request)(nil),   // 16: hugo.v1.storage.StreamWrite.Request
	(*StreamWrite_Response)(nil),  // 17: hugo.v1.storage.StreamWrite.Response
	(*DeleteBlock_Request)(nil),   // 18: hugo.v1.storage.DeleteBlock.Request
	(*DeleteBlock_Response)(nil),  // 19: hugo.v1.storage.DeleteBlock.Response
	(*ListBlocks_Request)(nil),    // 20: hugo.v1.storage.ListBlocks.Request
	(*ListBlocks_BlockMeta)(nil),  // 21: hugo.v1.storage.ListBlocks.BlockMeta
	(*ListBlocks_Response)(nil),   // 22: hugo.v1.storage.ListBlocks.Response
	(*EvictBlock_Request)(nil),    // 23: hugo.v1.storage.EvictBlock.Request
	(*EvictBlock_Response)(nil),   // 24: hugo.v1.storage.EvictBlock.Response
	(*RecycleSpace_Request)(nil),  // 25: hugo.v1.storage.RecycleSpace.Request
	(*RecycleSpace_Response)(nil), // 26: hugo.v1.storage.RecycleSpace.Response
	(*Warmup_Request)(nil),        // 27: hugo.v1.storage.Warmup.Request
	(*Warmup_Response)(nil),       // 28: hugo.v1.storage.Warmup.Response
}
var file_storage_storage_proto_depIdxs = []int32{
	1,  // 0: hugo.v1.storage.StreamReadResponse.block:type_name -> hugo.v1.storage.Block
	1,  // 1: hugo.v1.storage.Read.Response.blocks:type_name -> hugo.v1.storage.Block
	15, // 2: hugo.v1.storage.StreamWrite.Request.header:type_name -> hugo.v1.storage.StreamWrite.Header
	0,  // 3: hugo.v1.storage.ListBlocks.BlockMeta.state:type_name -> hugo.v1.storage.BlockState
	21, // 4: hugo.v1.storage.ListBlocks.Response.blocks:type_name -> hugo.v1.storage.ListBlocks.BlockMeta
	11, // 5: hugo.v1.storage.StorageService.Read:input_type -> hugo.v1.storage.Read.Request
	11, // 6: hugo.v1.storage.StorageService.StreamRead:input_type -> hugo.v1.storage.Read.Request
	13, // 7: hugo.v1.storage.StorageService.Write:input_type -> hugo.v1.storage.WriteBlock.Request
	16, // 8: hugo.v1.storage.StorageService.StreamWrite:input_type -> hugo.v1.storage.StreamWrite.Request
	18, // 9: hugo.v1.storage.StorageService.DeleteBlock:input_type -> hugo.v1.storage.DeleteBlock.Request
	20, // 10: hugo.v1.storage.StorageService.ListBlocks:input_type -> hugo.v1.storage.ListBlocks.Request
	23, // 11: hugo.v1.storage.StorageService.EvictBlock:input_type -> hugo.v1.storage.EvictBlock.Request
	25, // 12: hugo.v1.storage.StorageService.RecycleSpace:input_type -> hugo.v1.storage.RecycleSpace.Request
	27, // 13: hugo.v1.storage.StorageService.Warmup:input_type -> hugo.v1.storage.Warmup.Request
	12, // 14: hugo.v1.storage.StorageService.Read:output_type -> hugo.v1.storage.Read.Response
	3,  // 15: hugo.v1.storage.StorageService.StreamRead:output_type -> hugo.v1.storage.StreamReadResponse
	14, // 16: hugo.v1.storage.StorageService.Write:output_type -> hugo.v1.storage.WriteBlock.Response
	17, // 17: hugo.v1.storage.StorageService.StreamWrite:output_type -> hugo.v1.storage.StreamWrite.Response
	19, // 18: hugo.v1.storage.StorageService.DeleteBlock:output_type -> hugo.v1.storage.DeleteBlock.Response
	22, // 19: hugo.v1.storage.StorageService.ListBlocks:output_type -> hugo.v1.storage.ListBlocks.Response
	24, // 20: hugo.v1.storage.StorageService.EvictBlock:output_type -> hugo.v1.storage.EvictBlock.Response
	26, // 21: hugo.v1.storage.StorageService.RecycleSpace:output_type -> hugo.v1.storage.RecycleSpace.Response
	28, // 22: hugo.v1.storage.StorageService.Warmup:output_type -> hugo.v1.storage.Warmup.Response
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_storage_storage_proto_init() }
func file_storage_storage_proto_init() {
	if File_storage_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Read); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlocks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvictBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleSpace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Warmup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Read_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Read_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteBlock_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteBlock_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamWrite_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamWrite_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamWrite_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlock_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlock_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlocks_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlocks_BlockMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlocks_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvictBlock_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvictBlock_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleSpace_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecycleSpace_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Warmup_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_storage_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Warmup_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_storage_storage_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_storage_storage_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*StreamWrite_Request_Header)(nil),
		(*StreamWrite_Request_Block)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_storage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_storage_proto_goTypes,
		DependencyIndexes: file_storage_storage_proto_depIdxs,
		EnumInfos:         file_storage_storage_proto_enumTypes,
		MessageInfos:      file_storage_storage_proto_msgTypes,
	}.Build()
	File_storage_storage_proto = out.File
	file_storage_storage_proto_rawDesc = nil
	file_storage_storage_proto_goTypes = nil
	file_storage_storage_proto_depIdxs = nil
}
