// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: storage/volume.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	VolumeService_MountVolume_FullMethodName = "/hugo.v1.storage.VolumeService/MountVolume"
	VolumeService_GetVolume_FullMethodName   = "/hugo.v1.storage.VolumeService/GetVolume"
	VolumeService_ListVolumes_FullMethodName = "/hugo.v1.storage.VolumeService/ListVolumes"
)

// VolumeServiceClient is the client API for VolumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VolumeServiceClient interface {
	MountVolume(ctx context.Context, in *MountVolume_Request, opts ...grpc.CallOption) (*MountVolume_Response, error)
	GetVolume(ctx context.Context, in *GetVolume_Request, opts ...grpc.CallOption) (*GetVolume_Response, error)
	ListVolumes(ctx context.Context, in *ListVolumes_Request, opts ...grpc.CallOption) (*ListVolumes_Response, error)
}

type volumeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeServiceClient(cc grpc.ClientConnInterface) VolumeServiceClient {
	return &volumeServiceClient{cc}
}

func (c *volumeServiceClient) MountVolume(ctx context.Context, in *MountVolume_Request, opts ...grpc.CallOption) (*MountVolume_Response, error) {
	out := new(MountVolume_Response)
	err := c.cc.Invoke(ctx, VolumeService_MountVolume_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) GetVolume(ctx context.Context, in *GetVolume_Request, opts ...grpc.CallOption) (*GetVolume_Response, error) {
	out := new(GetVolume_Response)
	err := c.cc.Invoke(ctx, VolumeService_GetVolume_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) ListVolumes(ctx context.Context, in *ListVolumes_Request, opts ...grpc.CallOption) (*ListVolumes_Response, error) {
	out := new(ListVolumes_Response)
	err := c.cc.Invoke(ctx, VolumeService_ListVolumes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeServiceServer is the server API for VolumeService service.
// All implementations should embed UnimplementedVolumeServiceServer
// for forward compatibility
type VolumeServiceServer interface {
	MountVolume(context.Context, *MountVolume_Request) (*MountVolume_Response, error)
	GetVolume(context.Context, *GetVolume_Request) (*GetVolume_Response, error)
	ListVolumes(context.Context, *ListVolumes_Request) (*ListVolumes_Response, error)
}

// UnimplementedVolumeServiceServer should be embedded to have forward compatible implementations.
type UnimplementedVolumeServiceServer struct {
}

func (UnimplementedVolumeServiceServer) MountVolume(context.Context, *MountVolume_Request) (*MountVolume_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MountVolume not implemented")
}
func (UnimplementedVolumeServiceServer) GetVolume(context.Context, *GetVolume_Request) (*GetVolume_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedVolumeServiceServer) ListVolumes(context.Context, *ListVolumes_Request) (*ListVolumes_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVolumes not implemented")
}

// UnsafeVolumeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeServiceServer will
// result in compilation errors.
type UnsafeVolumeServiceServer interface {
	mustEmbedUnimplementedVolumeServiceServer()
}

func RegisterVolumeServiceServer(s grpc.ServiceRegistrar, srv VolumeServiceServer) {
	s.RegisterService(&VolumeService_ServiceDesc, srv)
}

func _VolumeService_MountVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountVolume_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).MountVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_MountVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).MountVolume(ctx, req.(*MountVolume_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolume_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).GetVolume(ctx, req.(*GetVolume_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_ListVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVolumes_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ListVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_ListVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ListVolumes(ctx, req.(*ListVolumes_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// VolumeService_ServiceDesc is the grpc.ServiceDesc for VolumeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hugo.v1.storage.VolumeService",
	HandlerType: (*VolumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MountVolume",
			Handler:    _VolumeService_MountVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _VolumeService_GetVolume_Handler,
		},
		{
			MethodName: "ListVolumes",
			Handler:    _VolumeService_ListVolumes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/volume.proto",
}
